### ISSUE TITLE
It is not valid for negative numbers.

### ISSUE THREAD

**Issue by VarshaSaroj** [cc-bhu/github-demo#2]
Fix the code for negative numbers.

**Comment by PradyumnaKrishna** [comment]
Thank you for submitting an issue but looks like it is a duplicate of #1 (Wrong factorial for negative numbers).

If you are looking to providing a fix to that issue, please submit a Pull Request.
Here is more information regarding contribution and creating a PR: https://github.com/CC-BHU/github-demo#contribution

Closing this as duplicate of #1.
